# Generated by Django 2.0.7 on 2018-07-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('photo', models.ImageField(blank=True, upload_to='blog/photos')),
                ('created_at', models.DateTimeField(editable=False)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
